[package]
name = "instant-distance-py"
version = "0.3.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
name = "instant_distance"
crate-type = ["cdylib"]

[dependencies]
bincode = "1.3.1"
instant-distance = { version = "0.5", path = "../instant-distance", features = ["with-serde"] }
pyo3 = { version = "0.14.1", features = ["extension-module"] }
serde = { version = "1", features = ["derive"] }
serde-big-array = "0.3.2"

[package.metadata.maturin]
name = "instant-distance"
